### ISSUE TITLE
narrower text on frontpage and navigation

### ISSUE THREAD

**Issue by bhpayne** [allofphysicsgraph/task-tracker#29]
currently text spans the entire page width on <https://derivationmap.net/> and <https://derivationmap.net/navigation>. Introduce left and right margins to improve readability.

**Comment by bhpayne** [comment]
Suggestions from Gemini 3:

To improve readability, the goal is to target an **optimal line length** (usually 600px to 800px). When lines are too long, the eye has trouble finding the start of the next line.

Here are three approaches to fix this, ranging from simple to "modern pro."

---

### Option 1: The "Main Container" (Simplest)
This is the most common method. You wrap your content in a `<div>` and use CSS to center it and limit its width.

**1. Add this to your `<style>` block:**
```css
.container {
    max-width: 800px;  /* Optimal reading width */
    margin: 0 auto;    /* Centers the container */
    padding: 0 20px;   /* Prevents text from touching edges on mobile */
}

/* Allow wide images to "break out" of the 800px limit */
.wide-content {
    width: 100vw;
    position: relative;
    left: 50%;
    right: 50%;
    margin-left: -50vw;
    margin-right: -50vw;
    text-align: center;
}

.wide-content img {
    max-width: 1000px; /* Or 100% to fill screen */
    height: auto;
}
```

**2. Update your HTML:**
Wrap everything from the `<h1>` down to the `<footer>` (or just inside the footer) in a `<div class="container">`. When you have a wide image, wrap it in the `wide-content` div.

```html
<body>
  <div class="container">
    <h1>Frequently Asked Questions...</h1>
    <p>Existing text content...</p>

    <!-- For a normal image -->
    <img src="small-img.png" style="max-width: 100%;">

    <!-- For a wide image that needs more space -->
    <div class="wide-content">
       <img src="/static/conceptual_physics_graph_actual_expressions_linked_by_variables.svg">
    </div>

    <p>More text...</p>
  </div>
</body>
```

---

### Option 2: The "Modern CSS Grid" (Cleanest)
This is the most robust way to handle "wide" and "narrow" content without using messy negative margins.

**1. Update your `<style>` block:**
```css
body {
    display: grid;
    /* Create 3 columns: side gutter, center content (max 800px), side gutter */
    grid-template-columns: 1fr min(800px, 100%) 1fr;
    column-gap: 20px;
}

/* Make every direct child of body go into the center column */
body > * {
    grid-column: 2;
}

/* Create a class for elements that should be wider (like your big graphs) */
.full-width {
    grid-column: 1 / 4;
    width: 100%;
    justify-self: center;
    text-align: center;
}

.full-width img {
    max-width: 1200px; /* Allow it to be wider than the text */
    width: 100%;
    height: auto;
}

/* Ensure the footer stays centered or spans */
footer {
    grid-column: 2;
    margin-top: 50px;
}
```

**2. Update your HTML:**
You don't need a wrapper! Just add the class `full-width` to your wide images or their parent `<center>` tags.

```html
<p>This text will automatically be centered and narrow.</p>

<div class="full-width">
    <img src="/static/wide-graph.svg">
</div>
```

---

### Option 3: Constraint by Element (No HTML changes)
If you don't want to change your HTML structure at all, you can target specific tags.

**Add this to your CSS:**
```css
/* Limit width of text-heavy elements */
p, ul, h1, h2, h3, blockquote, hr {
    max-width: 800px;
    margin-left: auto;
    margin-right: auto;
    padding-left: 20px;
    padding-right: 20px;
}

/* Ensure images and tables don't overflow on mobile */
img, table {
    max-width: 100%;
    height: auto;
    display: block;
    margin: 20px auto;
}

/* Keep your existing center tags for wide images as they are, 
   or specifically target the wide IDs if you have them */
```

---

### Important Bonus: Mobile Tables
Since you have a large `table` in your "Use Cases" section, tables often break mobile layouts. Add this to your CSS to allow users to swipe left/right on the table if it's too wide for their phone:

```css
table {
    display: block;
    overflow-x: auto;
    white-space: nowrap;
}
```

### Recommendation:
Use **Option 1**. It is the most compatible with older browsers and is very easy to debug. 

- Wrap everything inside `<body>` with `<div class="container">`.
- For the specific image `conceptual_physics_graph_actual_expressions_linked_by_variables.svg` (which you mentioned is wide), use the `wide-content` trick provided in Option 1. 
- This will keep your FAQ text readable while letting your complex graphs breathe.
